# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Oliver Upton
email: upton.oliver@gmail.com
host: 0.0.0.0
description: > # this means to ignore newlines until "baseurl:"
  Senior in ECE at UT Austin, Software Engineer Intern at Microsoft.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.oupton.ml" # the base hostname & protocol for your site
github_username: oupton

# Build settings
markdown: kramdown
